### ISSUE TITLE
Download table feature doesn't work on Safari (Mac OS)

### ISSUE THREAD

**Issue by GenevieveBuckley** [microscopium/microscopium#111]
As discussed here https://github.com/bokeh/bokeh/pull/8381#issuecomment-434561611  the download table feature doesn't work on Safari.

We should put a note in the README to say we currently only support Chrome.

Longer term, it would be good to test across most OS/browser configurations:
* OSX: safari, FF, chrome
* Windows: IE11, Edge, FF, Chrome
* Linux: FF, Chrome

**Comment by jni** [comment]
> We should put a note in the README to say we currently only support Chrome.

And Firefox. ;) I use FF and it works fine.

In general, web development is a huge mess and I have no interest in supporting any variant that is not W3C standards compliant. e.g. in the Bokeh example there's a "support for IE" clause which I find very off-putting.
