### ISSUE TITLE
Add Haralick features

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium#129]
Iva mentioned that texture features are very handy in some screens and might do better in the current screen anyway. These can be implemented with `skimage.feature.greycoprops`.

**Comment by GenevieveBuckley** [comment]
Should the Haralick features be computed on: the entire image, or small patches within the image?

**Comment by jni** [comment]
The whole image. Just like with the current features, small patches *could* be pulled out, optionally, to speed up computation.
