### ISSUE TITLE
KeyError: 'url' when trying to run

### ISSUE THREAD

**Issue by lucyleeow** [microscopium/microscopium#136]
I tried running microscopium using a data set cleaned by @jni. The first 10 lines of the data file are attached: [data2.txt](https://github.com/microscopium/microscopium/files/2744016/data2.txt)

The command I ran was `python -m microscopium.serve /Volumes/Iva/petermac/vi/out/data.csv`

I get this error:
 
> Traceback (most recent call last):
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3078, in get_loc
>     return self._engine.get_loc(key)
>   File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'url'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/liulucy/Documents/microscopium/microscopium/serve.py", line 413, in <module>
>     run_server_cmd()
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/liulucy/Documents/microscopium/microscopium/serve.py", line 398, in run_server_cmd
>     run_server(filename, config=config, path=path, port=port)
>   File "/Users/liulucy/Documents/microscopium/microscopium/serve.py", line 405, in run_server
>     makedoc = make_makedoc(filename, config)
>   File "/Users/liulucy/Documents/microscopium/microscopium/serve.py", line 343, in make_makedoc
>     dataframe = dataframe_from_file(filename)
>   File "/Users/liulucy/Documents/microscopium/microscopium/serve.py", line 33, in dataframe_from_file
>     df['path'] = df['url'].apply(lambda x: join(dirname(filename), x))
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/pandas/core/frame.py", line 2688, in __getitem__
>     return self._getitem_column(key)
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
>     return self._get_item_cache(key)
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
>     values = self._data.get(item)
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/pandas/core/internals.py", line 4115, in get
>     loc = self.items.get_loc(item)
>   File "/Users/liulucy/anaconda3/envs/mic/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
>     return self._engine.get_loc(self._maybe_cast_indexer(key))
>   File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'url'

And running the app at localhost 500 gives '500:Internal Server Error'

**Comment by jni** [comment]
@lucyleeow thanks for the report! You were running into two separate issues. The first is that you are not calling the right `data.csv` file. The file you've opened is the one with all 246(ish) features. The file you want has those features reduced to a couple. To get it to work, you need `info3.csv`.

The second issue is that when I made that file, we hadn't yet finished #93, and anyway that wasn't quite ready for action. So you need to:

- rename the columns in `info3.csv`. `x` becomes `x.tsne` and `y` becomes `y.tsne`. You can do this with a text editor such as nano or vim, it's just editing the very first line.
- copy the example `settings.yaml` file that I have pointed out in #137 to sit next to `info3.csv`.
- change `group` to `library` (this is the column that you want to colour points by)
- under `tooltip-columns`, replace `url` with `compound` and add an extra line for `concentration`.
- for that huge dataset, you might actually want to reduce `glyph_size`. Worth playing around with that number.

And you also need to wait for #137 to be merged and reinstall microscopium. :grimacing: I hope that happens tonight! =)

I'm going to close this, reopen if your problem isn't fixed after #137.

**Comment by GenevieveBuckley** [comment]
FYI pull request https://github.com/microscopium/microscopium/pull/137 has just been merged. You can try downloading microscopium and reinstalling it now - please let us know if that hasn't fixed your problem.
