### ISSUE TITLE
Bokeh server: dynamically determine static/ location from which to serve images (etc)

### ISSUE THREAD

**Issue by GenevieveBuckley** [microscopium/microscopium#152]
Open issue to track the discussion at: https://discourse.bokeh.org/t/bokeh-server-dynamically-determine-static-location-from-which-to-serve-images-etc/3223/3

I don't trust myself to remember this link if I don't have an open issue for it. Happy for it to be moved to a comment on a more appropriate issue, if there's one I missed.

Juan asks:
> We’re building an image viewer/browser with Bokeh server. Currently, when a user selects one or more points in a scatter plot, using a Python callback:
> * the corresponding images are loaded into NumPy arrays from the file paths
> * then these are displayed in a separate canvas using image_rgb
>
> This turns out to not be super-performant, and I thought it’s probably wasteful to decompress on the server. I don’t know what Bokeh is doing in the background but I imagine either re-compressing to transfer to the browser, or transferring the uncompressed data. Either of these approaches is pretty wasteful, so I presume that image_url would be faster. I’ve read the previous post on the topic [1] where Bryan posted some very specific advice about how to structure the app directory:
>
>> * make a “directory” style app
>> * make a “static” subdirectoy in the app directory
>> * put all your pngs, etc in the “static” subdirectoy
>> * then anything in the static directory is available at the relative URL “myappname/static” (substitute whatever your actual app name is for“myappname”)
>
> And, further dashing my hopes and dreams:
>
>> Just to be clear, it’s never going to be possible to load files from
arbitrary filesystem locations like “C:/foo/bar.png”, only from the application-specific “static” directory.
>
> Now, please correct my logic if I’m wrong, but I presume that there is an asterisk to the above statement: Bokeh must somehow be serving up that directory, and it should be possible to make it serve some other arbitrary directory (tree), rather than one specifically named “static” in a specific part of the filesystem. So I have two questions:
>
> How is Bokeh serving up the static directory? Can you point me to the right part of the Bokeh codebase? We are calling the Bokeh server manually [2], so we need to figure this out anyway, even if serving from static/.
>
> Alternatively, is there a more effective way to send the jpg from the server to the “Image” object, rather than decompressing on the server?
>
> Thanks,
> Juan.
>
> … [1] https://groups.google.com/a/continuum.io/forum/#!msg/bokeh/gUlflToHbk8/X1TKUvSsCgAJ
>
> … [2] https://github.com/microscopium/microscopium/blob/0236e53fc0e8eaf10b0dd5f33d14fa6d1ce002fe/microscopium/bokeh_app.py#L184-L191

And Bryan replies:
> Top level static routes (i.e. that serve BokehJS) are configured here:
>
>  https://github.com/bokeh/bokeh/blob/master/bokeh/server/urls.py
>
> Per-app static routes are configured here, based on app.static_path (if present):
>
>  https://github.com/bokeh/bokeh/blob/master/bokeh/server/tornado.py#L253-L260
>
> Bokeh is a Tornado application, and those are all Tornado views. If you run the Bokeh server programmatically you can certainly add any additional Tornado view you need, including additional StaticHandler instances.
>
> FWIW I am interested in Image glyphs that could send PNGs/JPGs to the client as-is, without needing to first convert them to RGBA arrays. I don't know when we might have the resources to do that, but I am happy to offer guidance to anyone that would like to work on it sooner.

**Comment by mrocklin** [comment]
Hey y'all.  You may want to look at this code in Dask which adds a static file handler to a Bokeh server

https://github.com/dask/distributed/blob/99ac4550d0231ae81076307dda8b821b51bc5792/distributed/dashboard/core.py#L33-L53

**Comment by GenevieveBuckley** [comment]
The relevant part to look at in that link is the `handlers` list.

```python
def run_server(filename, config=None, path='/', port=5000):
    """Run the bokeh server."""
    makedoc = make_makedoc()
    apps = {path: Application(FunctionHandler(makedoc))}

    server = Server(apps, port=port, allow_websocket_origin=['*'])
    handlers = [
        (
            r"/example_data/(.*)",
            web.StaticFileHandler,
            {"path": os.path.join(os.path.dirname(__file__), "static")},
        )
    ]
    server._tornado.add_handlers(r".*", handlers)
    server.run_until_shutdown()
```
