### ISSUE TITLE
Clean up old mongo code

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium#153]
A lot of code depends on the mongodb model we originally developed. I think now that mongo is way overkill and we should use simple database or even dataframe models together with the filesystem for the images. Scalability might be an issue, but for the time being I anticipate microscopium to be single-machine-single-dataset deployments only.

**Comment by GenevieveBuckley** [comment]
PR https://github.com/microscopium/microscopium/pull/157 removed mongo from this project. But we have two mongo related files left behind in the test folders, they should be deleted as well:
* microscopium/tests/testdata/mongodb/.gitkeep
* microscopium/tests/testdata/mongodb/dummy_empty_file
