### ISSUE TITLE
config.yml - recursive formatting all numeric values to float

### ISSUE THREAD

**Issue by GenevieveBuckley** [microscopium/microscopium#159]
So if we ever want to recursively loop through nested dictionaries created with `yaml.safe_load()` and turn any numeric values into floats, I recently wrote code to do this in another project.

https://github.com/DeMarcoLab/fibsem/pull/63/files

```python
import yaml


def load_config(yaml_filename):
    """Load user input from yaml settings file.
    Parameters
    ----------
    yaml_filename : str
        Filename path of user configuration file.
    Returns
    -------
    dict
        Dictionary containing user input settings.
    """
    with open(yaml_filename, "r") as f:
        settings = yaml.safe_load(f)
    settings = _format_dictionary(settings)
    return settings


def _format_dictionary(dictionary):
    """Recursively traverse dictionary and covert all numeric values to flaot.
    Parameters
    ----------
    dictionary : dict
        Any arbitrarily structured python dictionary.
    Returns
    -------
    dictionary
        The input dictionary, with all numeric values converted to float type.
    """
    for key, item in dictionary.items():
        if isinstance(item, dict):
            _format_dictionary(item)
        elif isinstance(item, list):
            dictionary[key] = [_format_dictionary(i) for i in item]
        else:
            if item is not None:
                try:
                    dictionary[key] = float(dictionary[key])
                except ValueError:
                    pass
    return dictionary
```

**Comment by jni** [comment]
erm, doesn't yaml already do this?

```python
In [4]: yaml_str = (
   ...: '''
   ...: hello:
   ...:   - 5.0
   ...:   - 5.0
   ...:   - 7.8
   ...: '''
   ...: )

In [5]: yaml.safe_load(yaml_str)
Out[5]: {'hello': [5.0, 5.0, 7.8]}
```

**Comment by GenevieveBuckley** [comment]
It seems the answer is... only sometimes?

Oooh, it only happens for a specific combination of:
* scientific notation
* that does *not* include a decimal point with at least one significant figure after it

```python
In [15]: yaml_str = ('''
    ...: hello:
    ...:   key1: 5e6
    ...:   key2: 2.e6
    ...:   key3: 7.0e6
    ...: ''')

In [16]: yaml.safe_load(yaml_str)
Out[16]: {'hello': {'key1': '5e6', 'key2': '2.e6', 'key3': '7.0e6'}}
```

**Comment by GenevieveBuckley** [comment]
I feel justified in keeping my workaround, I think many people (including me) will want to type "1e6" for one micron on a reasonably regular basis.

Do you think this is intended behaviour by the yaml library?

**Comment by jni** [comment]
That's just super annoying! It works with capital E:

```python
In [6]: yaml_str = (
   ...: '''
   ...: hello:
   ...:   - 5.0E-6
   ...:   - 5.0e6
   ...:   - 7.8
   ...: '''
   ...: )

In [7]: yaml.safe_load(yaml_str)
Out[7]: {'hello': [5e-06, '5.0e6', 7.8]}
```

**Comment by jni** [comment]
I'm not sure whether it's intended. Would be worth digging around in their github issues to see whether this has come up before. The fact that they allow E and not e to me suggests that either (1) it's intentional because maybe E is universal across languages but e is just a Python-specific shortcut,or (2) it's unintentional because the authors have never seen e, and they'd be open to adding it.

Yeah ok that's not helpful. But probably reading around will disambiguate the two. imho for microscopium I prefer we stick with the yaml spec, where spec = what pyyaml does. =P

**Comment by GenevieveBuckley** [comment]
That's not quite it either. 

Check this out:

```python
In [1]: import yaml

In [2]: yaml_str = ('''
   ...: hello:
   ...:   - 5.0E6
   ...:   - 5.0e6
   ...:   - 5.E6
   ...:   - 5.e6
   ...:   - 5E6
   ...:   - 5e6
   ...: ''')

In [3]: yaml.safe_load(yaml_str)
Out[3]: {'hello': ['5.0E6', '5.0e6', '5.E6', '5.e6', '5E6', '5e6']}

In [4]: yaml_str = ('''
   ...: hello:
   ...:   - 5.0E-6
   ...:   - 5.0e-6
   ...:   - 5.E-6
   ...:   - 5.e-6
   ...:   - 5E-6
   ...:   - 5e-6
   ...: ''')

In [5]: yaml.safe_load(yaml_str)
Out[5]: {'hello': [5e-06, 5e-06, 5e-06, 5e-06, '5E-6', '5e-6']}
```

**Comment by GenevieveBuckley** [comment]
Anyway, we're getting off track.

If the workaround is useful for this project also, we can use it. If we're not doing any scientific notation entries in the config file, there's no need for this.

**Comment by jni** [comment]
:man_facepalming: 

I think it's a useful discussion, but let's close this for now, and disallow this kind of notation in our config. We know where to come looking again if we end up needing it. Thanks!
