### ISSUE TITLE
Investigate SQLite3 as Mongo alternative

### ISSUE THREAD

**Issue by starcalibre** [microscopium/microscopium#19]
A small app I'm working on is using SQLite3 for the database, and I think it offers a few advantages over MongoDB, especially for a single-user app like ours that will be run locally.

Pros:
- Database lives in self contained file, no daemon is required to access the data. This is the big advantage.
- Smaller footprint than Mongo.
- Well supported in Python/Node.js

Cons: 
- Key-value pairs of documents in Mongo feel more 'Pythonic'
- Data is not kept natively as JSON document (parsers exist however)
- SQL syntax
- Does not support arrays as a value type.

Seeing as I am writing code to process the Cellomics files, I thought it might be worth trialling SQLite for storing data. Any thoughts?

**Comment by starcalibre** [comment]
A potential MongoDB alternative is NeDB -- https://github.com/louischatriot/nedb

This is like the Mongo/NoSQL version of SQLite3. I'm just unsure about its Python compatibility. This is something I'll look into. I'd really like this to work *without* users needing a local Mongo instance running.

**Comment by starcalibre** [comment]
I've looked into these further, and here are my thoughts..

SQLite3 is a great embedded SQL database, but the lack of support for arrays as a datatype is a deal breaker. There's no way around this other than setting up a separate table for our array data and using lots of joins, so I'm nixing this idea. That being said, it's one of the most pleasant SQL implementations I've used so I highly recommend it if the need for a relational DB ever arises. :)

NeDB on the other hand, I think this is going to suit us well. It's a subset of the Mongo API, and uses the exact same syntax as Mongoose. The only difference is, the data is kept in a self-contained file so you don't need a Mongo instance running. There's no Python module available for NeDB, but it stores databases as a plain JSON file. Datasets could quite easily be exported as JSON files after analysis. Loading the data into the UI would then just be a matter of selecting the file you're interested in. I really quite like this, as it eliminates the need for users to have a Mongo instance and it makes data much more portable. I quite like the idea of running the image analysis on a cluster, then downloading the datafile and loading this up into the UI. Microscopium files could quite easily be shared between users too, without the need to mess around with mongo import/export.

**Comment by jni** [comment]
In Python it's trivial to launch a mongo instance — would that not be the case in JS also? Although I fully agree about the advantages of self-contained files, I'm quite worried about performance. If you can show me some benchmarks for this that show that it's comparable, I'd be happy to condone the switch. =)

**Comment by starcalibre** [comment]
Launching a sub-process is trivial in Node too :) It's more what happens after the subprocess is launched that I'm worried about. 

I can't seem to find any good benchmarks out offering a fair comparison between MongoDB and SQLite.. I'm surprised given the magnitude of the NoSQL vs SQL holy war. But I guess it makes sense, seeing it's not a like-for-like comparison.

I might convert one of the Cellomics datasets over to SQLite and do some benchmarks on that. I think it's worth doing as it will make for some good results both for my thesis/progress report and to publish as a blogpost.

**Comment by jni** [comment]
I agree that it would be a valuable addition to the global record of information and flaming. =P But I thought SQLite itself was out? Or are you using it as a catchall term?

**Comment by starcalibre** [comment]
SQLite isn't quite out! At first I was dubious about using join tables because SQL join queries get complicated and messy quickly, but I've been playing around with two Object Relation Mappers for Python (see https://peewee.readthedocs.org/en/latest/ ) and Node (see see http://sequelizejs.com/). As suggested by their names, they map objects to relational models so inserting and querying for data from SQL databases becomes Mongo-like. They also make dealing with joins really easy. I really wish I knew about these earlier, it would've made my past encounters with SQL much more pleasant!

NeDB is out, it pooped the bed when I tried to load the JSON file with all the images!

**Comment by jni** [comment]
Right, so NeDB pooped the bed so you are using a library called peewee to get around the problems with SQLite. 




If I hadn't seen your interface working I'd conclude you were just messing with me. =P

**Comment by GenevieveBuckley** [comment]
We removed mongo in PR https://github.com/microscopium/microscopium/pull/157, so this issue is outdated and no longer relevant.

**Comment by GenevieveBuckley** [comment]
We removed mongo in PR https://github.com/microscopium/microscopium/pull/157, so this issue is outdated and no longer relevant.
