### ISSUE TITLE
A bug in the sq_to_dist function

### ISSUE THREAD

**Issue by sahas111** [microscopium/microscopium#26]
Hi, the sq_to_dist function in metrics.py is returning a wrong index. The test call in the doc_string also returns the wrong value.

**Comment by jni** [comment]
@starcalibre I spent some time with @sahas111 trying to prove that her computation was wrong (=P), but in fact this does look like a bug! It's quite obvious that the docstring test should return 2, not 1! I think the `-1` in the computation is the culprit and removing it will fix everything.

"The hardest problem in computer science is whether to add one, subtract one, or just leave the damn thing alone." — Mike Waterman. =D

Having said that, with 0 indexing, leaving it alone is usually the right answer!
