### ISSUE TITLE
Add tSNE to the dimensionality-reduction methods

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium#36]
http://lvdmaaten.github.io/tsne/

**Comment by starcalibre** [comment]
Say we have three different dimension reduction techniques.. PCA, MDS, tSNE. The database schema should have a field for each sample that's set out like this:

```
dimension_reduced: {
    pca: [0, 0],
    mds: [0, 0],
    tsne: [0, 0]
}
```

Then if a user so wishes, they can change how they'd like the data to appear in an options menu somewhere.

If anything, having this functionality would be useful for development.. as we add more datasets we can easily see how different dimension reduction techniques perform.

**Comment by jni** [comment]
I would add further components, not just the first two. Then a user can try to plot the 1st and 3rd component, for example. Or, there can be a toggle to use opacity, size, colour, etc, to plot the third dimension. And so forth.

Also, remember that MDS with Euclidean distances is equivalent to PCA! =P

Other than that, your schema looks good!

**Comment by jni** [comment]
@starcalibre I'm working on the tSNE now. (As you can see on our [gitter](https://gitter.im/microscopium/microscopium).) My current schema is flat, `pca_vector`, `tsne_vector`, etc. Since this requires a corresponding change in microscopium/microscopium-ui, we should definitely coordinate carefully. I think flat is better, because it translates more easily to e.g. CSV, or other DBs.

In other news, [here's](https://github.com/scikit-learn/scikit-learn/pull/4025#issuecomment-93887261) a very nice procedural summary of the steps in tSNE. It might actually be easy enough to roll our own Barnes-Hut version if we don't worry too much about optimisation... Something to think about.

**Comment by starcalibre** [comment]
The upside to the nested/non-flat setup I proposed is each screen can have a different number of dimensionality techniques applied to it and have the UI adapt easily, as it'll just need to traverse the ``dimension_reduced`` object to find all the different embeddings.

**Comment by jni** [comment]
Ah, you're right of course. I guess it's straightforward enough to "unroll" nested fields anyway.
