### ISSUE TITLE
Check for signal when doing image normalisation/illumination correction

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium#38]
Some images contain no signal in one of the channels (for example, when none of the cells express the target protein). When stretchlim is applied, the remaining background noise gets amplified, resulting in a "haze", resulting in bad visualisation and probably bad feature extraction. Coming up with a test that would suppress noise instead of applying stretchlim in these situations would fix this.

@starcalibre can you provide one good and one bad example from the public screen?

**Comment by starcalibre** [comment]
Good: 
![as_09125-50116110001-a19](https://cloud.githubusercontent.com/assets/7637964/6611327/1c31f530-c8bf-11e4-97f9-fd832fdb88e7.jpg)
Bad:
![as_09125-50116110001-f23](https://cloud.githubusercontent.com/assets/7637964/6611329/205e99e2-c8bf-11e4-932c-02bb35cd3ecf.jpg)

**Comment by jni** [comment]
Possible solution: adjust the contrast only once per screen or per plate, and remember those stretch parameters for the full set of images. So the vmin vmax is set globally, not once per image.

**Comment by jni** [comment]
@starcalibre are these from the same plate? Can you tell me their coordinates so I can see if #44 works on a non-toy dataset?

**Comment by starcalibre** [comment]
These are from the same plate.. barcode 50116110001 (or folder NIRHTa-001). The co-ordinates are A19 and F23.

**Comment by jni** [comment]
woot! Thanks!

**Comment by jni** [comment]
@starcalibre BOOM. Done with the new illumination correction and command line for streaming stitching:

![_as_09125_50116110001_a19](https://cloud.githubusercontent.com/assets/492549/6961543/d6acdd8a-d977-11e4-99c9-f8ac33ad0549.png)

![_as_09125_50116110001_f23](https://cloud.githubusercontent.com/assets/492549/6961545/d7519de8-d977-11e4-8abe-4fc91801f59c.png)
