### ISSUE TITLE
Make a full run of the HT29 dataset

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium#40]
This dataset will be our public demo so it needs to be fully incorporated into our testing, and added to the microscopium.io machine.

- [x] nomalise, stitch, stack images
- [x] extract features
- [x] build mongo

**Comment by jni** [comment]
Whoo! One down! That was quick... =P

@starcalibre see https://github.com/microscopium/microscopium-scripts/pull/5

**Comment by jni** [comment]
The cool thing is that with the new streaming data system I can do it all in ~30CPU.h, virtually no memory required! Now I just need an easy, convenient way to parallelise... ;)

**Comment by starcalibre** [comment]
What's the best way to do this in Python these days? The ``multiprocessing`` module?

**Comment by jni** [comment]
I'm not really sure... I think IPython.parallel is the best choice currently. (Soon to be jupyter_parallel I think...!)

**Comment by jni** [comment]
Did this! I love it when you go over issues and discover they're finished! =P
