### ISSUE TITLE
Add command-line interface to build mongoDB for a new screen

### ISSUE THREAD

**Issue by jni** [microscopium/microscopium#41]
Related to microscopium/microscopium-scripts#4

The interface should allow:
- adding of the screen description to the Screens collection
- adding of the sample description to the Samples collection
- selecting or creating the "Treatment" column for the Samples collection
- adding the images to the Images collection
- _optionally_, actually generating the stitched/stacked images to add to Images

**Comment by starcalibre** [comment]
This seems like an appropriate issue to mention this.. the [BBBC022](https://www.broadinstitute.org/bbbc/BBBC022/) dataset comes with a metadata file were each row represents a filename. In each row there's information such as plate barcode, channel, library barcode, plate well co-ordinate, capture field, etc. Basically everything you need to go from files -> Mongo documents ready to be displayed in the UI.

I think this is the approach we should take with defining a metadata format for adding a new screen to microscopium. Creating an appropriate metadata file for inputting new screens should be an easy task for any bioinformatician, then that file should guide the process of stitching, feature extraction, etc. That way it'll be extensible to pretty much any HCS system.data format for adding a new screen to microscopium. Creating an appropriate metadata file for inputting new screens should be an easy task for any bioinformatician, then that file should guide the process of stitching, feature extraction, etc. That way it'll be extensible to pretty much any HCS system.

**Comment by GenevieveBuckley** [comment]
We removed mongo in PR https://github.com/microscopium/microscopium/pull/157, so this issue is outdated and no longer relevant.
