### ISSUE TITLE
Bokeh prototype

### ISSUE THREAD

**Issue by birdsarah** [microscopium/microscopium#73]
Sorry for the delay @jni, I finished making a prototype with bokeh.

![microscopium-bokeh](https://cloud.githubusercontent.com/assets/1796208/18025793/4ea8a04e-6be9-11e6-8f3c-5a4a1b8a3e24.gif)

You can see it here: https://github.com/birdsarah/microscopium/tree/bokeh_proto

**Comment by jni** [comment]
Hi @birdsarah! Great to hear from you! Sorry for the long delay, was on holiday when you sent this!

Very cool! In the next few days I'll try to clean up the big dataset, and fiddle with this code to get it running on it! We'll have to figure out how to fix the overplotting. At which point you would be very much welcome to host it, or point to our own hosted instance!

By the way, for some reason the neighbours render *bigger* than the selected image on my (tiny screen) laptop:

<img width="1238" alt="screen shot 2016-09-10 at 7 10 40 pm" src="https://cloud.githubusercontent.com/assets/492549/18409486/88e559ac-778b-11e6-9c65-5b463b07ed74.png">

**Comment by birdsarah** [comment]
That's probably a css issue. What's in your developer console?

**Comment by jni** [comment]
You'll have to be more precise in your question... =) I have never done web dev, so I don't know what to look for...

**Comment by jni** [comment]
Actually, this is interesting:

<img width="1260" alt="screen shot 2016-09-10 at 7 31 10 pm" src="https://cloud.githubusercontent.com/assets/492549/18409562/31123d88-778d-11e6-867f-71df20ab218a.png">

**Comment by birdsarah** [comment]
On Firefox: Tools -> Developer Tools -> Network.

Then reload the page.

**Comment by jni** [comment]
Ok so you want to know what CSS is loaded? I see:

http://localhost:5006/static/css/bokeh-widgets.min.css?v=522d6173498a389c7f74f0e675195da0
http://localhost:5006/static/css/bokeh.min.css?v=12cad2d8ad9f63966dc6553746de780f

**Comment by birdsarah** [comment]
> Actually, this is interesting

It's a CSS thing.

So, that's the problem. What version of bokeh are you using? The CSS that's specified with the external model isn't being registered.

**Comment by birdsarah** [comment]
My list also includes `image_select.css`

**Comment by birdsarah** [comment]
I'm on 0.12.2 - which is required for this feature.

**Comment by jni** [comment]
I'm on 0.12.0. Updating. Could also be some silly Chrome security thing. Hold please!

**Comment by jni** [comment]
Boom! Updating worked! =)

**Comment by jni** [comment]
ok it's dinner time here... More later! Thank you! =)

**Comment by birdsarah** [comment]
Bye. Just a heads up, the next two weeks are a bit crazy - next week in particular.

**Comment by jni** [comment]
Oh great! Don't stress, I'm not in a hurry, just didn't want to neglect you after all your work on this! =)

**Comment by GenevieveBuckley** [comment]
This is very cool. I'm going to close this issue now that it's been a while and the current bokeh interface has drifted away slightly from the implementation described here.

**Comment by jni** [comment]
@birdsarah :wave: Hope things are great. Would love to show you what we've done with your template someday. =)

**Comment by birdsarah** [comment]
@jni - I would love that. I live in Austin now, so if you're ever back for SciPy let me know.

**Comment by jni** [comment]
@birdsarah I missed you at this year's SciPy! Hoping to be back next year for sure. =)
